
=== https://codelabs.developers.google.com/codelabs/flutter-codelab-first#0[Namer App: Your First Flutter App]

[source, bash]
flutter create namer_app

Under `name_app`
[source, bash]
flutter run

and choose your development target (e.g. MacOS).

----
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
----

Edit the file `lib/main.dart`


[source,dart]
----
// Change the color and press r to hotreload
colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepOrange),
----

https://fluttergems.dev/packages/english_words/

[source,bash]
flutter pub add english_words

`pubspec.yaml`
[source,yaml]
----
include::3-1-NamerApp/3-CreateAProject/pubspec.yaml[lines=30]
include::3-1-NamerApp/3-CreateAProject/pubspec.yaml[lines=38]
----

`lib/main.dart`
[source,dart]
----
include::3-1-NamerApp/3-CreateAProject/main.dart[lines=2]
include::3-1-NamerApp/3-CreateAProject/main.dart[lines=28..31]

----

https://pub.dev/packages/provider

[source,bash]
flutter pub add provider

`pubspec.yaml`
[source,yaml]
----
include::3-1-NamerApp/3-CreateAProject/pubspec.yaml[lines=30]
include::3-1-NamerApp/3-CreateAProject/pubspec.yaml[lines=39]
----

`lib/main.dart`
[source,dart]
----
include::3-1-NamerApp/3-CreateAProject/main.dart[lines=10..27]
include::3-1-NamerApp/3-CreateAProject/main.dart[lines=33..37]
    ...
  }
}
----

[TIP]
====
For IntelliJ IDEA, when focusing `lib/main.dart`, you can choose the target as `macOS (desktop)` in the top-right corner and then click the right triangle button to deploy the application. If you run the application in this way, when you save the file using `COMMAND + S`, it will hot-reload automatically.
====

==== Add a Button

[source,dart]
----
include::3-1-NamerApp/4-MakeAButton/main.dart[lines=6..8]
----
<1> Run the app named `MyApp` from `main`.

[source,dart]
----
include::3-1-NamerApp/4-MakeAButton/main.dart[lines=10..27]

include::3-1-NamerApp/4-MakeAButton/main.dart[lines=29..31]
----
<1> `ChangeNotifierProvider` creates and provides the state for the app.
<2> The state class `MyAppState` extends `ChangeNotifier` to notify others about its own changes.

[mermaid]
----
classDiagram
  class MyApp
  class MyAppState
  MyApp *--  MyHomePage
  MyApp *-- MyAppState
  MyHomePage *--  SomeWidget
  MyHomePage *--  OtherWidget
  class OtherWidget
  OtherWidget --> MyAppState : Watches and uses
----

`lib/main.dart`
[source,dart]
----
include::3-1-NamerApp/4-MakeAButton/main.dart[lines=33..50]
----
<1> `MyHomePage` tacks change to the state using the `watch` method by the context
<2> Add a button, it will print a message to the debug console

==== Add Next Behavior for the Button


`lib/main.dart`
[source,dart]
----
include::3-1-NamerApp/4-MakeAButton/main2.dart[lines=29..36]
----
<1> Use `notifyListeners()` to make anyone watching `MyAppState` get notified.

`lib/main.dart`
[source,dart]
----
include::3-1-NamerApp/4.2-ButtonNext/main.dart[lines=48..50]
----

==== Extract Widget

// https://stackoverflow.com/questions/57105154/shortcut-to-extract-flutter-widget-from-ui-layout


`lib/main.dart`
[source,dart]
----
include::3-1-NamerApp/4-MakeAButton/main2.dart[lines=46]
----
Move cursor on the widget then `right click` > `refactor` > `Extract Flutter widget`


`lib/main.dart`
[source,dart]
----
include::3-1-NamerApp/5-ExtractWidget/BigCard.dart[lines=2..14]
----

<1> Move cursor on the widget then `Right click` > `Show context actions` > `Wrap with padding`


`lib/main.dart`
[source,dart]
----
include::3-1-NamerApp/5-ExtractWidget/BigCard2.dart[lines=11..16]
----


`lib/main.dart`
[source,dart]
----
include::3-1-NamerApp/5-ExtractWidget/BigCard3.dart[lines=11..18]
----
<1> Wrap with card

`lib/main.dart`
[source,dart]
----
include::3-1-NamerApp/5-ExtractWidget/BigCard4.dart[lines=11..21]
----
<1> Get context
<2> Use primary color from theme

`lib/main.dart`
[source,dart]
----
include::3-1-NamerApp/5-ExtractWidget/BigCard5.dart[lines=11..24]
----
<1> Get style from text theme
<2> Apply style to text

Use `CMD + SPACE` with some space or next line to show available options like `color`


`lib/main.dart`
[source,dart]
----
include::3-1-NamerApp/5-ExtractWidget/MyHomePage.dart[lines=2..21]
----
<1> Align to the vertical axis for the column

At the bottom of your run console, you see three buttons(`Flutter Hot Reload`, `Flutter Hot Restart`, `Open Flutter Dev Tools`) and one vertical dots button.

Click `Open Flutter Dev Tools` for the https://docs.flutter.dev/tools/devtools/inspector[Flutter Inspector].

You can check that `Text`, `BigCard`, and `ElevatedButton` are in the center of `Column` but the `Column` is to the right of the `Scaffold`.

In Flutter Inspector, click `Select Widget Mode`, then come back to click the column in your application, you can see that the column just occupy the left part of the whole application which means that it is not centered.

`lib/main.dart`
[source,dart]
----
include::3-1-NamerApp/5-ExtractWidget/MyHomePage2.dart[lines=2..22]
----
<1> Wrap `Column` in `Center`
<2> Add spacing using `SizedBox`