=== https://www.freecodecamp.org/news/learn-flutter-full-course/[Flutter Course for Beginners - 37-hour Mobile App Development Tutorial]

https://www.youtube.com/watch?v=VPvVD8t02U8[YouTube]

https://www.youtube.com/watch?v=VPvVD8t02U8&t=4483s[Chapter 3 - Introduction to Dart]

[source,bash]
----
flutter create learningdart
----

https://code.visualstudio.com/docs/setup/mac[Add Visual Studio Code path] to your `.zshrc`.

[source,bash]
----
export PATH=/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin:$PATH
----


`CMD + Shift + P` to open the command palette, then type `Flutter: Select Device`. Another way to select device to to use the FLUTTER plugin by clicking the icon on the left panel.

Click `Run` > `Start Debugging` to run the app.

After the app is launched, if you are developing Web applications, you can open the Flutter DevTools and check the `Flutter Inspector`.

`Shift` + `Option` + `F` to format the code. https://stackoverflow.com/questions/29973357/how-do-you-format-code-in-visual-studio-code-vscode[SO] https://dart.dev/tools/dart-format[dart format]

https://www.youtube.com/watch?v=VPvVD8t02U8&t=7286s[Chapter 4 - Dart control statements and collections]

https://www.youtube.com/watch?v=VPvVD8t02U8&t=10005s[Chapter 5 - Sound Null-safety in Dart]


[source,dart]
----
include::null1.dart[lines=2]
----

where `??` is called the [if-null operator, or null-coalescing operator](https://dart.dev/language/operators). See https://dart.dev/null-safety/understanding-null-safety[understanding null safety]. Also read https://dart.dev/null-safety[null-safety].

variable `!`  where `!` is called non-null assertion operator. See https://dart.dev/language/operators#other-operators[operators].

`??=` operator only assigns when the variable is null. See https://dart.dev/language/operators#other-operators[??=].

`?.` is the conditional invocation operator.

https://www.youtube.com/watch?v=VPvVD8t02U8&t=12432s[Chapter 6 - Dart enumerations, classes and objects]

For VS Code, hover over some text and use `CMD` + `.` to see suggestions.

https://dart.dev/language/constructors#factory-constructors[Factory constructors].

For overriding an existed method of the super class, you need to use the `covariant` keyword. See https://stackoverflow.com/questions/71237639/functioning-of-covariant-in-flutter[SO] for the related discussions.

https://www.youtube.com/watch?v=VPvVD8t02U8&t=15517s[Chapter 7 - Advanced Dart]

https://www.youtube.com/watch?v=VPvVD8t02U8&t=18040s[Chapter 8 - Project setup]

[source,bash]
----
flutter create --org org.freecodecamp.test mynotes
----

[source,bash]
flutter upgrade

`CMD` + `F` or `CMD` + `Shift` + `F` to search in the project.

[source,bash]
----
flutter pub add firebase_core
flutter pub add firebase_auth
flutter pub add cloud_firestore
flutter pub add firebase_analytics
----

==== https://www.youtube.com/watch?v=VPvVD8t02U8&t=27092s[Chapter 11 - Firebase Backend Setup]


https://firebase.flutter.dev/docs/overview/[Flutter Fire]

https://firebase.google.com/docs/flutter/setup?hl=zh-tw&platform=ios[Google Firebase]

[source,bash]
dart pub global activate flutterfire_cli

[source,bash]
flutterfire configure

* Create a new project, e.g. `mynotes-0f8jkl5c`. Don't use upper case letters.

[source,text]
----
Exception: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- xcodeproj (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
----


https://stackoverflow.com/questions/36485180/how-to-update-ruby-with-homebrew[Ruby envrionment]

[source,bash]
----
brew install rbenv
rbenv install 3.4.1
rbenv global 3.4.1
ruby --version
gem install xcodeproj
gem install cocoapods

flutterfire configure
----

* Note that you need to add  `eval "$(rbenv init -)"` to your .zshrc

After configuration, check `lib/firebase_options.dart` for your setup.

[source,text]
----
@horaciocoronel
00:00:11 Chapter 0 - Presentation
00:02:58 Chapter 1 - Developer Accounts
00:39:12 Chapter 2 - Setup
01:14:43 Chapter 3 - Introduction to Dart
02:01:26 Chapter 4 - Dart control statements and collections
02:46:45 Chapter 5 - Sound Null-safety in Dart
03:27:12 Chapter 6 - Dart enumerations, classes and objects
04:18:37 Chapter 7 - Advanced Dart
05:00:40 Chapter 8 - Project setup
05:48:30 Chapter 9 - iOS App Setup (App Identifier, Certificates and Profiles)
06:59:33 Chapter 10 - Android app Setup
07:31:32 Chapter 11 - Firebase Backend Setup
----



==== https://www.youtube.com/watch?v=VPvVD8t02U8&t=28881s[Chapter 12 - Basic register-user screen]

`stl` for Stateless Widget, `stf` for Stateful Widget.

If lookup fails, try hot restart.

`CMD` + `.` for suggestions.

https://firebase.google.com/docs/auth[Firebase Auth]

https://firebase.google.com/docs/auth/flutter/start[Firebase Auth for Flutter]

[source,bash]
flutter pub add firebase_auth

[source,text]
----
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
----

https://stackoverflow.com/questions/72880037/unhandled-exception-platformexceptionchannel-error-unable-to-establish-connec[SO]

[source,bash]
----
flutter pub outdated
----

[source, xml]

Add the following lines to `macos/Runner/DebugProfile.entitlements` and  `macos/Runner/ReleaseProfile.entitlements`

----
    <key>com.apple.security.network.client</key>
    <true/>
----

[source,text]
----
Error: The pod "Firebase/CoreOnly" required by the plugin "firebase_core" requires a higher minimum macOS deployment version than the plugin's reported minimum version.
To build, remove the plugin "firebase_core", or contact the plugin's developers for assistance.
Error: Error running pod install
----

Change `Podfile` from `platform :osx, '10.14'` to `platform :osx, '15.0'` https://stackoverflow.com/questions/78052754/the-pod-firebase-firestore-required-by-the-plugin-cloud-firestore-requires-a[SO]

[source,dart]
----
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'firebase_options.dart';


void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp( options: DefaultFirebaseOptions.currentPlatform,);
  runApp(MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const HomePage(),
    ));
}
----

Add `Authentication > email/password` in your https://console.firebase.google.com/[Firebase console]

[source,text]
----
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: [firebase_auth/keychain-error] An error occurred when accessing the keychain. The NSLocalizedFailureReasonErrorKey field in the NSError.userInfo dictionary will contain more information about the error encountered
----

I use `flutter run` again and the above error just gone and introduce another error below. If you change your email, then the above error occurs again.

[source,text]
----
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: [firebase_auth/email-already-in-use] The email address is already in use by another account.
----

https://github.com/firebase/flutterfire/issues/11186[SO]
https://medium.com/@1998.singh.amarjit/save-credentials-autofill-credentials-in-flutter-33058295dd9d[TODO: Keychain]
https://firebase.google.com/docs/ios/setup[Note: If you're targeting macOS or macOS Catalyst, you must add the Keychain Sharing capability to your target. In Xcode, navigate to your target's Signing & Capabilities tab, and then click + Capabilities to add a new capability.]
https://stackoverflow.com/questions/72956366/firebase-auth-reports-keychain-error-on-ios-while-working-fine-on-android-flu[SO THIS!!!]


https://docs.flutter.dev/resources/architectural-overview#architectural-layers[Flutter architecture layers]

Use `FutureBuilder`.

`Shift` + `Option` + `F` to format code in VS code.

==== https://www.youtube.com/watch?v=VPvVD8t02U8&t=32694s[Chapter 13 - Login view]

[source,bash]
----
flutterfire configure # Choose web and macos
----

`F2` to rename symbol.

`CMD` + click to go to the definition.

==== https://www.youtube.com/watch?v=VPvVD8t02U8&t=35590s[Chapter 14 - Separating app initialization from login/register]

==== https://www.youtube.com/watch?v=VPvVD8t02U8&t=37188s[Chaper 15 - Git and Github]

==== https://www.youtube.com/watch?v=VPvVD8t02U8&t=40234s[Chapter 16 - Email Verification View]

==== https://www.youtube.com/watch?v=VPvVD8t02U8&t=42285s[Chapter 17 - Link Between login and register views]

==== https://www.youtube.com/watch?v=VPvVD8t02U8&t=44281s[Chapter 18 - Logout view]

==== https://www.youtube.com/watch?v=VPvVD8t02U8&t=47627s[Chapter 19 - Go From Login to Notes View]

[source,dart]
----
import 'dart:developer' as devtools show log;
----

[source,text]
----
08:01:21 Chapter 12 - Basic register-user screen
09:04:54 Chapter 13 - Login view
09:53:10 Chapter 14 - Separating app initialization from login/register
10:19:48 Chapter 15 - Git and Github
11:10:34 Chapter 16 - Email Verification View
11:44:45 Chapter 17 - Link Between login and register views
12:18:01 Chapter 18 - Logout view
13:13:47 Chapter 19 - Go From Login to Notes View
----

==== https://www.youtube.com/watch?v=VPvVD8t02U8&t=49004s[Cahpter 20 - Cleaning Up our Routes]

==== https://www.youtube.com/watch?v=VPvVD8t02U8&t=49877s[Chapter 21 - Error Handling in Login View]

==== https://www.youtube.com/watch?v=VPvVD8t02U8&t=51381s[Chapter 22 - Error Handling in Register View and Going to Next Screen After Registration]

If you modify the main function, you need to hot restart the app.

==== https://www.youtube.com/watch?v=VPvVD8t02U8&t=53085s[Chapter 23 - Confirming Identity Before Going to Main UI]

[source,text]
----
13:36:44 Chapter 20 - Cleaning Up our Routes
13:51:17 Chapter 21 - Error Handling in Login View
14:16:21 Chapter 22 - Error Handling in Register View and Going to Next Screen After Registration
14:44:45 Chapter 23 - Confirming Identity Before Going to Main UI
----

==== https://www.youtube.com/watch?v=VPvVD8t02U8&t=53542s[Chapter 24 - Auth Service]

==== https://www.youtube.com/watch?v=VPvVD8t02U8&t=57322s[Chapter 25 - Migrating to Auth Service]

==== https://www.youtube.com/watch?v=VPvVD8t02U8&t=59621s[Chapter 26 - Unit Testing our Auth Service]

[source,bash]
----
flutter pub add test --dev
----

[source,bash]
flutter build web # For build test package

[source,bash]
flutter test test/auth_test.dart

[source,text]
----
14:52:22 Chapter 24 - Auth Service
15:55:22 Chapter 25 - Migrating to Auth Service
16:33:41 Chapter 26 -  Unit Testing our Auth Service
----

==== https://www.youtube.com/watch?v=VPvVD8t02U8&t=61463s[Chapter 27 - CRUD Local Storage]

`NN`: not NULL

`PK`: Primary Key: Primary key implies uniqueness.

`AI`: Auto Increment

`U`: Unique

[source,sql]
----
CREATE TABLE "user" (
	"id"	INTEGER NOT NULL,
	"email"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
----

[source,sql]
----
CREATE TABLE "note" (
	"id"	INTEGER NOT NULL,
	"user_id"	INTEGER NOT NULL,
	"text"	TEXT,
	"is_synced_with_cloud"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("user_id") REFERENCES "user"("id")
);
----

https://pub.dev/[Flutter pub]

[source,bash]
flutter pub add sqflite path_provider path

==== https://www.youtube.com/watch?v=VPvVD8t02U8&t=70257s[Chapter 28 - Working with Streams in Notes Service]

==== https://www.youtube.com/watch?v=VPvVD8t02U8&t=72272s[Chapter 29 - Preparing Notes View to Read All Notes]

==== https://www.youtube.com/watch?v=VPvVD8t02U8&t=74362s[Chapter 30 - Preparing to Create New Notes]

==== https://www.youtube.com/watch?v=VPvVD8t02U8&t=77011s[Chapter 31 - Creating New Notes]

https://github.com/tekartik/sqflite/tree/master/packages_web/sqflite_common_ffi_web#setup-binaries[Sqflite on web]

[source,bash]
----
# flutter pub add sqflite_common_ffi # For other platforms
flutter pub add sqflite_common_ffi_web # For web
dart run sqflite_common_ffi_web:setup
----

==== https://www.youtube.com/watch?v=VPvVD8t02U8&t=83272s[Chapter 32 - Displaying Notes in Notes View]

==== https://www.youtube.com/watch?v=VPvVD8t02U8&t=85415s[Chapter 33 - Deleting Existing Notes in Notes View]

==== https://www.youtube.com/watch?v=VPvVD8t02U8&t=87624s[Chapter 34 - Updating Existing Notes]

[source]
----
17:43:43 Chapter 27 - CRUD Local Storage
19:30:57 Chapter 28 - Working with Streams in Notes Service
20:04:32 Chapter 29 - Preparing Notes View to Read All Notes
20:39:22 Chapter 30 - Preparing to Create New Notes
21:00:16 Chapter 31 - Creating New Notes
21:35:43 Chapter 32 - Displaying Notes in Notes View
21:56:04 Chapter 33 - Deleting Existing Notes in Notes View
22:40:46 Chapter 34 - Updating Existing Notes
----

==== https://www.youtube.com/watch?v=VPvVD8t02U8&t=92319s[Chapter 35 - Protecting NotesService with Current User]

[source,text]
----
For `Stream<List<DatabaseNote>> get allNotes => _notesStreamController.stream.map((notes) => notes);`, I have a runtime error: TypeError: Instance of '_MapStream<List<DatabaseNote>, dynamic> is not a subtype of type 'Stream<List<DatabaseNote>>'
----

The error is due to the fact that the map function returns a new stream that emits the results of applying the provided function to each event of the original stream.

[source,dart]
----
Stream<List<DatabaseNote>> get allNotes => _notesStreamController.stream.map((notes) => notes).cast<List<DatabaseNote>>();
Stream<List<DatabaseNote>> get allNotes => _notesStreamController.stream.map((notes) => notes) as Stream<List<DatabaseNote>>;
Stream<List<DatabaseNote>> get allNotes => _notesStreamController.stream.cast<List<DatabaseNote>>();
----

We just need to declare the type of the stream as `Stream<List<DatabaseNote>>`.

[source,dart]
late final StreamController<List<DatabaseNote>> _notesStreamController;

==== https://www.youtube.com/watch?v=VPvVD8t02U8&t=85244s[Chapter 36 - Writing Notes to Cloud Firestore]

[source]
----
23:14:12 Chapter 35 - Protecting NotesService with Current User
23:40:44 Chapter 36 - Writing Notes to Cloud Firestore
24:58:08 Chapter 37 - Migrating to our Firestore Service
25:22:36 Chapter 38 - Sharing Notes
25:37:44 Chapter 39 - Introduction to Bloc
26:24:31 Chapter 40 - Converting our Auth Process to Bloc
27:31:17 Chapter 41 - Handling Auth Bloc Exceptions During Login
27:52:45 Chapter 42 - Moving to Bloc for Routing and Dialogs
29:58:23 Chapter 43 - Loading Screens
29:48:31 Chapter 44 - Final Touches Before App Release
30:43:03 Chapter 45 - App Icons and app Name
31:06:34 Chapter 46 - Splash Screen
31:56:59 Chapter 47 - Sending our iOS app to App Store Connect
32:55:44 Chapter 48 - Releasing our iOS App
33:20:32 Chapter 49 - Fixing Firebase Security Rules and Resubmitting the iOS App
34:50:07 Chapter 50 - Releasing our Android App
34:55:19 Chapter 51 - Localization in Flutter
36:33:57 Outro - Final thoughts
----